import FolderIcon from "@mui/icons-material/Folder";
import DescriptionIcon from "@mui/icons-material/Description";
import { authRoles } from "./auth/authRoles";

export const navigations = [
  
  {
    name: "Price Book",
    icon: <FolderIcon fontSize="small" />,
    role:authRoles.admin,
    children: [
      {
        name: "Print Price Book",
        path: "/pages/pricing-portal/view-price-book",
        iconText: "P",
        accessID: "PPB002",
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
        fav : false,
      },
      {
        name: "Print Price Book Group",
        path: "/pages/pricing-portal/run-price-book",
        iconText: "PP",
        accessID: "PPB004",
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
        fav : false,
      },
    ],
  },
  {
    name: "Quote",
    icon: <FolderIcon fontSize="small" />,
    role: authRoles.admin,
    children: [
      {
        name: "New Quote",
        icon: <DescriptionIcon fontSize="small" />,
        path: "/pages/pricing-portal/quote-form",
        role: authRoles.admin,
        accessID: "PPB005",
        iconText: "V",
        fav : false,
      },
      {
        name: "Templates",
        icon: <DescriptionIcon fontSize="small" />,
        path: "/pages/pricing-portal/quote-template",
        role: authRoles.admin,
        accessID: "PPB0010",
        iconText: "QT",
        fav : false,
      },
    ],
  },



  //======================================+CONTROL-PANEL============================================//
  {
    name: "CP-Price Book",
    icon: <FolderIcon fontSize="small" />,
    role: authRoles.admin,
    children: [
      {
        name: "Items",
        path: "/pages/control-panel/items",
        iconText: "I",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
      {
        name: " Price List",
        path: "/pages/control-panel/company-price-list",
        iconText: "P",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
  
      {
        name: "Price Book Categories",
        path: "/pages/control-panel/print-group",
        iconText: "P",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
    
      {
        name: "Run Group",
        path: "/pages/control-panel/company-run-group",
        iconText: "R",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
      {
        name: "Configure Price Book",
        path: "/pages/control-panel/configure-price-book/company",
        iconText: "C",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
    ],
  },

  {
    name: "Security",
    icon: <FolderIcon fontSize="small" />,
    role: authRoles.admin,
    children: [
      {
        name: "Company",
        path: "/pages/security/company",
        iconText: "V",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
      {
        name: "Application",
        path: "/pages/security/application",
        iconText: "B",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
      {
        name: "User Group",
        path: "/pages/security/user-group",
        iconText: "B",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
      {
        name: "User",
        path: "/pages/security/user",
        iconText: "B",
        accessID: null,
        icon: <DescriptionIcon fontSize="small" />,
        role: authRoles.admin,
      },
    ],
  },
];
export const favMenu = [
  {
    name: "home",
    path: "/home",
    iconText: "H",
    accessID: "PPB001",
    icon: <DescriptionIcon fontSize="small" />,
    role: authRoles.user,
  },
  {
    name: "Print Price Books",
    path: "/pages/view-price-book",
    iconText: "V",
    accessID: "PPB002",
    icon: <DescriptionIcon fontSize="small" />,
    role: authRoles.user,
  },
  // {
  //   name: "Build Custom Price Book",
  //   path: "/pages/price-book/build-custom",
  //   iconText: "B",
  //   accessID: "PPB003",
  //   icon: <DescriptionIcon fontSize="small" />,
  //   role: authRoles.user,
  // },
  {
    name: "Run Price Book",
    path: "/pages/run-price-book",
    iconText: "C",
    accessID: "PPB004",
    icon: <DescriptionIcon fontSize="small" />,
    role: authRoles.user,
  },
  {
    name: "Quote",
    icon: <DescriptionIcon fontSize="small" />,
    path: "/pages/quote-form",
    role: authRoles.user,
    accessID: "PPB005",
    iconText: "V",
  },
  {
    name: "View Directory",
    path: "/pages/view-directory",
    iconText: "V",
    icon: <DescriptionIcon fontSize="small" />,
    accessID: "PPB006",
    role: authRoles.user,
  },
  {
    name: "Add New Contact",
    path: "/pages/add-new-contact",
    accessID: "PPB007",
    iconText: "V",
    icon: <DescriptionIcon fontSize="small" />,
    role: authRoles.user,
  },
  {
    name: "Edit Price Book",
    icon: <DescriptionIcon fontSize="small" />,
    path: "/pages/edit-price-book",
    role: authRoles.user,
    accessID: "PPB008",
    iconText: "E",
  },
  {
    name: "Price Book Template",
    icon: <DescriptionIcon fontSize="small" />,
    path: "/pages/price-book-template",
    role: authRoles.user,
    accessID: "PPB009",
    iconText: "P",
  },
  {
    name: "Quote Template",
    icon: <DescriptionIcon fontSize="small" />,
    path: "/pages/quote-template",
    role: authRoles.user,
    accessID: "PPB0010",
    iconText: "QT",
  },
  {
    name: "Specials",
    icon: <DescriptionIcon fontSize="small" />,
    path: "/pages/specials",
    role: authRoles.user,
    accessID: "PPB0011",
    iconText: "S",
  },
  {
    name: "Configure Price Book",
    icon: <DescriptionIcon fontSize="small" />,
    path: "/pages/price-book/configure",
    role: authRoles.admin,
    accessID: "PPB0012",
    iconText: "C",
  },
];




// export const navigations = [
//   {
//     name: "Price Book",
//     icon: <FolderIcon fontSize="small" />,
//     children: [
//       {
//         name: "Print Price Book",
//         path: "/pages/view-price-book",
//         iconText: "P",
//         accessID: "PPB002",
//         icon: <DescriptionIcon fontSize="small" />,
//         role: authRoles.user,
//         fav : false,
//       },
//       // {
//       //   name: "Build Custom Price Book",
//       //   path: "/pages/price-book/build-custom",
//       //   iconText: "B",
//       //   accessID: "PPB003",
//       //   icon: <DescriptionIcon fontSize="small" />,
//       //   role: authRoles.user,
//       //   fav : false,
//       // },
//       {
//         name: "Print Price Book Group",
//         path: "/pages/run-price-book",
//         iconText: "PP",
//         accessID: "PPB004",
//         icon: <DescriptionIcon fontSize="small" />,
//         role: authRoles.user,
//         fav : false,
//       },
//     ],
//   },
//   {
//     name: "Quote",
//     icon: <DescriptionIcon fontSize="small" />,
//     path: "/pages/quote-form",
//     role: authRoles.user,
//     accessID: "PPB005",
//     iconText: "V",
//     fav : false,
//   },
//   {
//     name: "Price Book Directory",
//     icon: <FolderIcon fontSize="small" />,
//     children: [
//       {
//         name: "View Directory",
//         path: "/pages/view-directory",
//         iconText: "V",
//         icon: <DescriptionIcon fontSize="small" />,
//         accessID: "PPB006",
//         role: authRoles.user,
//         fav : false,
//       },
//       {
//         name: "Add New Contact",
//         path: "/pages/add-new-contact",
//         accessID: "PPB007",
//         iconText: "V",
//         icon: <DescriptionIcon fontSize="small" />,
//         role: authRoles.user,
//         fav : false,
//         // mode:add
//       },
//     ],
//   },
//   {
//     name: "Edit Price Book",
//     icon: <DescriptionIcon fontSize="small" />,
//     path: "/pages/edit-price-book",
//     role: authRoles.user,
//     accessID: "PPB008",
//     iconText: "E",
//     fav : false,
//   },
//   {
//     name: "Price Book Templates",
//     icon: <DescriptionIcon fontSize="small" />,
//     path: "/pages/price-book-template",
//     role: authRoles.user,
//     accessID: "PPB009",
//     iconText: "P",
//     fav : false,
//   },
//   {
//     name: "Quote Templates",
//     icon: <DescriptionIcon fontSize="small" />,
//     path: "/pages/quote-template",
//     role: authRoles.user,
//     accessID: "PPB0010",
//     iconText: "QT",
//     fav : false,
//   },
//   {
//     name: "Specials",
//     icon: <DescriptionIcon fontSize="small" />,
//     path: "/pages/specials",
//     role: authRoles.user,
//     accessID: "PPB0011",
//     iconText: "S",
//   },
//   {
//     name: "Configure Price Book",
//     icon: <DescriptionIcon fontSize="small" />,
//     path: "/pages/price-book/configure",
//     role: authRoles.admin,
//     accessID: "PPB0012",
//     iconText: "C",
//     fav : false,
//   },

//   //     {
//   //       name: "Add New Contact",
//   //       path: "/pages/add-new-contact",
//   //       iconText: "B",
//   //       accessID: null,
//   //       icon: <DescriptionIcon fontSize="small" />,
//   //       role: authRoles.user,
//   //     },
//   //     {
//   //       name: "Run Price Book",
//   //       path: "/pages/run-price-book",
//   //       iconText: "B",
//   //       accessID: null,
//   //       icon: <DescriptionIcon fontSize="small" />,
//   //       role: authRoles.user,
//   //     },
//   //   ],
//   // },
// ];
